language: php

php:
    - 5.4
    - 5.5

install:
    - composer install --prefer-dist --no-interaction

script:
   - phpunit -c app/ --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

